module.exports = ["safebrowsing.googleapis.com",
    "push.services.mozilla.com",
    "content-signature-2.cdn.mozilla.net",
    "aus5.mozilla.org",
    "firefox.settings.services.mozilla.com",
    "shavar.services.mozilla.com",
    "contile.services.mozilla.com",
    "download.mozilla.org",
    "services.addons.mozilla.org",
    "detectportal.firefox.com",
    "classify-client.services.mozilla.com",
    "versioncheck-bg.addons.mozilla.org",
    "normandy.cdn.mozilla.net",
    "region1.google-analytics.com",
    "www.googletagmanager.com",
    "dc.services.visualstudio.com",
]